### ISSUE TITLE
Switch DE

### ISSUE THREAD

**Issue by parham-dev27** [jackdeadman/quad#7]
Currently there is no way to switch the DE upon login.

**Comment by jackdeadman** [comment]
I'll have a look at implementing this. Feel free to give it a go if you have time

**Comment by parham-dev27** [comment]
how do I build the project?
I get this error: sh: line 1: node_modules/gulp/bin/gulp.js: No such file or directory

**Comment by jackdeadman** [comment]
It's been a while since I've developed this but just got it running, you may need an old version of node to be installed (doesn't matter too much because it's just for building). I used `nvm` to do this. This worked for me:

```
$ nvm install 10
$ nvm use 10
$ rm package-lock.json
$ npm install
$ npm run dev
```

Then open your browser to `http://localhost:8000`. If you get an error like failed to GET / restart the server and refresh. These steps worked for me.

**Comment by parham-dev27** [comment]
question: why do you use sass and not scss?

**Comment by jackdeadman** [comment]
I think I just preferred it 6 years ago

**Comment by parham-dev27** [comment]
Do you want me to convert it to scss? or do you still prefer it today?

**Comment by jackdeadman** [comment]
Feel free to change

**Comment by parham-dev27** [comment]
Hey, hope you're doing well. I finally had free time and rewrote the whole project. [Quad](https://github.com/parham-dev27/Quad) 
Thanks for the great project!

**Comment by jackdeadman** [comment]
No worries, good to see it have some attention :) I no longer daily drive linux so it wasn't something I had planned to work on in the foreseeable future
